deployment:
  tasks:
    - export DEPLOYPATH=/home/vrww25h9acfy/
    - /bin/cp -R public_html $DEPLOYPATH
    - export DEPLOYPATH=/home/vrww25h9acfy/public_html
    - /bin/cp -R views $DEPLOYPATH
    - /bin/pwd >> /etc/logs/cpanel.log
    - export VIDEOPATH=/home/vrww25h9acfy/
    - /bin/pwd ../ >> /etc/logs/cpanel.log
    - /bin/cp -R /home/vrww25h9acfy/repositories/videos $VIDEOPATH
    - export IMAGEPATH=/home/vrww25h9acfy/images/
    - /bin/cp -R ../images $IMAGEPATH
   
